const $=id=>document.getElementById(id), canvas=$('unity-canvas');
let instance=null,loadingPromise=null,inStudio=false,cancelled=false,keys=new Set(),drag=null,currentPanel=null,lastFocus=null,renderer='';
const coarse=matchMedia('(pointer:coarse)').matches, reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
$('quality').value=coarse?'low':'high';
function send(method,value=''){if(instance)instance.SendMessage('StudioExperience',method,String(value));}
function stop(){keys.clear();send('SetMove','0,0');drag=null;}
function setView(index){const names=['Make yourself at home.','Where ideas take shape.','The Backbenchers crew.','A moment of quiet.'];$('view-number').textContent=`0${index+1} / ${['THE ROOM','THE WORKBENCH','BOUNTY GALLERY','QUIET CORNER'][index]}`;$('view-title').textContent=names[index];document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.view)===index)));}
function showStudio(){inStudio=true;document.body.classList.add('exploring');document.body.classList.remove('loading');$('welcome').hidden=true;$('corner-note').hidden=true;$('tour').hidden=false;$('loading').hidden=true;send('SetPaused','0');send('SetQuality',$('quality').value);sizeCanvas();canvas.focus();}
function welcome(){inStudio=false;stop();send('SetPaused','1');document.body.classList.remove('exploring');$('welcome').hidden=false;$('corner-note').hidden=false;$('tour').hidden=true;$('enter').disabled=false;$('enter').querySelector('span').textContent=instance?'Return to the studio':'Step inside';$('enter').focus();}
function loadUnity(){if(loadingPromise)return loadingPromise;
loadingPromise=(async()=>{const response=await fetch('unity/build.json?v=2');if(!response.ok)throw Error('Studio build is not available.');const build=await response.json();await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='unity/'+build.loader;script.onload=resolve;script.onerror=()=>reject(Error('Could not load the studio engine.'));document.head.appendChild(script);});
const base='unity/';const config={dataUrl:base+build.data,frameworkUrl:base+build.framework,codeUrl:base+build.wasm,streamingAssetsUrl:base+'StreamingAssets',companyName:'Backbenchers Studio',productName:'Backbenchers Studio',productVersion:'1.1',matchWebGLToCanvasSize:true,devicePixelRatio:coarse?1:Math.min(devicePixelRatio,1.5),showBanner:(message,type)=>{if(type==='error'){$('load-error').hidden=false;$('load-error').textContent='The 3D studio could not start on this device. Your portfolio links below remain available.';console.error(message);}},print:message=>console.log(message),printErr:message=>console.warn(message)};
const app=await window.createUnityInstance(canvas,config,progress=>{$('progress').style.width=Math.round(progress*100)+'%';$('loading-label').textContent=progress<.9?`Opening the doors… ${Math.round(progress*100)}%`:'Arranging the studio…';});instance=app;return app;})();return loadingPromise;}
$('enter').onclick=async()=>{cancelled=false;$('load-error').hidden=true;if(instance){showStudio();return;}$('enter').disabled=true;$('loading').hidden=false;document.body.classList.add('loading');try{await loadUnity();if(!cancelled)showStudio();else{welcome();$('loading').hidden=true;}}catch(error){console.error(error);loadingPromise=null;document.body.classList.remove('loading');$('loading').hidden=true;$('load-error').textContent='We couldn’t open the 3D studio. Please reload and try again, or explore the selected work and full portfolio.';$('load-error').hidden=false;$('enter').disabled=false;}};
$('cancel-load').onclick=()=>{cancelled=true;$('loading-label').textContent='The studio is loading in the background. Browse the work while it finishes.';};
$('home').onclick=welcome;
function sizeCanvas(){if(!instance)return;send('SetViewport',innerWidth/innerHeight<.8?'portrait':'landscape');const dpr=$('quality').value==='low'?1:Math.min(devicePixelRatio,1.5);if(instance.Module)instance.Module.devicePixelRatio=dpr;canvas.style.width='100%';canvas.style.height='100%';}
$('quality').onchange=()=>{send('SetQuality',$('quality').value);sizeCanvas();};
for(const button of document.querySelectorAll('[data-view]'))button.onclick=()=>{stop();const i=Number(button.dataset.view);send('Visit',(reduced?'instant:':'')+i);setView(i);};
function updateMove(){let x=0,y=0;if(keys.has('w')||keys.has('arrowup'))y++;if(keys.has('s')||keys.has('arrowdown'))y--;if(keys.has('a')||keys.has('arrowleft'))x--;if(keys.has('d')||keys.has('arrowright'))x++;send('SetMove',`${x},${y}`);}
addEventListener('keydown',e=>{if(!inStudio||currentPanel||['INPUT','SELECT','BUTTON','A'].includes(document.activeElement.tagName))return;const k=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(k)){e.preventDefault();keys.add(k);updateMove();}});
addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());updateMove();});addEventListener('blur',stop);
canvas.onpointerdown=e=>{if(!inStudio||currentPanel||e.button!==0)return;canvas.focus();canvas.setPointerCapture(e.pointerId);drag={id:e.pointerId,x:e.clientX,y:e.clientY};};
canvas.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;send('Look',`${e.clientX-drag.x},${e.clientY-drag.y}`);drag.x=e.clientX;drag.y=e.clientY;};
canvas.onpointerup=canvas.onpointercancel=canvas.onlostpointercapture=()=>{drag=null;};
for(const b of document.querySelectorAll('[data-move]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);send('SetMove',b.dataset.move);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>send('SetMove','0,0');}
for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>{stop();if(currentPanel)currentPanel.close();lastFocus=b;currentPanel=$(b.dataset.panel);send('SetPaused','1');currentPanel.showModal();};
for(const d of document.querySelectorAll('dialog')){d.querySelector('[data-close]').onclick=()=>d.close();d.addEventListener('close',()=>{if(currentPanel!==d)return;currentPanel=null;if(inStudio)send('SetPaused','0');lastFocus?.focus();});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});}
document.addEventListener('visibilitychange',()=>{stop();send('SetPaused',document.hidden||!inStudio||currentPanel?'1':'0');});addEventListener('resize',sizeCanvas);
addEventListener('backbenchers-ready',e=>{renderer=e.detail.renderer;document.documentElement.dataset.renderer=renderer;});addEventListener('backbenchers-view',e=>setView(e.detail.index));
