export function createDesktop({power,preview}){
 const $=id=>document.getElementById(id),dialog=$('desktop'), storageKey='backbenchers-workspace-v1';
 let worker=null,pending=new Map(),serial=0,boot=null,snapshot={},busy=0,cwd='/home/studio',folder='/home/studio',device='thomas',powered=true,history=[],historyIndex=0,currentApp='home',remote=null,remoteConfig=null;
 try{snapshot=JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{}
 let active=false,paintTimer=0;
 const previewCanvas=document.createElement('canvas');previewCanvas.width=1024;previewCanvas.height=576;
 const names={thomas:'Thomas · Software & games',hlaing:'Hlaing · Content & design',merlin:'Merlin · Research lab',benchphone:'Workbench phone',phone:'Studio phone',tablet0:'Creative tablet 1',tablet1:'Creative tablet 2'};
 function paint(){clearTimeout(paintTimer);if(!active||!powered||document.hidden)return;paintTimer=setTimeout(paintNow,180);}
 function paintNow(){
  if(!active||!powered||document.hidden)return;const canvas=previewCanvas;const c=canvas.getContext('2d');c.setTransform(4/3,0,0,4/3,0,0);const g=c.createLinearGradient(0,0,768,432);g.addColorStop(0,'#29473b');g.addColorStop(1,'#49634a');c.fillStyle=g;c.fillRect(0,0,768,432);c.fillStyle='#182c26';c.fillRect(0,0,768,30);c.fillStyle='#f7e9ef';c.font='12px Arial';c.fillText('Backbenchers · '+(names[device]||device),18,20);c.fillText('Studio OS',680,20);c.fillStyle='#1c332b';c.fillRect(0,30,50,402);c.font='20px monospace';['◉','>_','▰','✎'].forEach((v,i)=>{c.fillStyle='#eedbe6';c.fillText(v,12,76+i*55);});c.fillStyle='#f6e9e0';c.font='26px Georgia';c.fillText(currentApp==='home'?'A little space to make things.':currentApp[0].toUpperCase()+currentApp.slice(1),82,98);
  c.fillStyle='#13241f';c.fillRect(78,124,660,261);c.fillStyle='#e5d8e7';c.font='12px monospace';let lines=currentApp==='terminal'?$('terminal-output').textContent.split('\n').slice(-14):currentApp==='editor'?$('editor-text').value.split('\n').slice(0,14):currentApp==='files'?Array.from($('files-list').children).map(b=>b.textContent):currentApp==='remote'?['UBUNTU / CREW WORKSTATION','',$('remote-status').textContent,'','Use the crew password to connect.','Local studio apps are available to visitors.']:['CREATE. CONNECT. BUILD.','','Terminal    Files    Editor','',device==='merlin'?'Merlin / flight research & connected devices.':device==='hlaing'?'Hlaing / stories, design & creative direction.':device==='thomas'?'Thomas / software, games & useful things.':'Backbenchers / notes, sketches & connected ideas.','Write a small program. Leave a note.','','Click this screen to use the computer.'];lines.forEach((line,i)=>c.fillText(line.slice(0,85),97,150+i*16));preview(device,canvas.toDataURL('image/jpeg',.86).split(',')[1]);
 }
 function log(text){$('terminal-output').textContent+=String(text).slice(0,100000);if($('terminal-output').textContent.length>200000)$('terminal-output').textContent=$('terminal-output').textContent.slice(-150000);$('terminal-output').scrollTop=$('terminal-output').scrollHeight;paint();}
 function status(text){$('desktop-status').textContent=text;}
 function halt(){worker?.terminate();worker=null;boot=null;for(const {reject}of pending.values())reject(Error('Stopped. Completed changes remain saved.'));pending.clear();busy=0;status('Runtime stopped · reopen an app to restart');}
 function request(data){return new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});worker.postMessage({...data,id});});}
 async function ensure(){if(boot)return boot;status('Starting Python workspace…');worker=new Worker(new URL('./python-worker.js',import.meta.url),{type:'module'});worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);if(data.snapshot){snapshot=data.snapshot;try{localStorage.setItem(storageKey,JSON.stringify(snapshot));}catch{status('Storage full · export files to keep them');}}if(data.error)p.reject(Error(data.error));else p.resolve(data);};worker.onerror=e=>{halt();status('Runtime unavailable · check your connection and retry');};boot=request({action:'init',snapshot}).then(()=>{status('Ready · files saved in this browser');return true;}).catch(error=>{boot=null;throw error;});return boot;}
 async function task(payload){busy++;$('terminal-run').disabled=true;try{await ensure();const r=await request(payload);if(r.cwd){cwd=r.cwd;$('terminal-prompt').textContent='studio@backbenchers:'+cwd.replace('/home/studio','~')+'$';}status('Saved locally · '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}));return r;}finally{busy--;if(busy<0)busy=0;$('terminal-run').disabled=busy>0;}}
 function app(name){currentApp=name;for(const p of document.querySelectorAll('[data-desktop-pane]'))p.hidden=p.dataset.desktopPane!==name;for(const b of document.querySelectorAll('[data-app]'))b.setAttribute('aria-pressed',String(b.dataset.app===name));$('desktop-app-title').textContent={remote:'Ubuntu 24.04 LTS',home:'Studio workspace',terminal:'Terminal',files:'Files',editor:'Text editor',about:'About this workspace'}[name];$('desktop').classList.toggle('remote-active',name==='remote');if(name==='remote')remote?.focus();if(name==='terminal')$('terminal-command').focus();if(name==='files')list(folder);paint();}
 async function list(path){try{const r=await task({action:'list',path});folder=r.path;$('files-path').value=folder;$('files-list').replaceChildren();for(const entry of r.entries){const b=document.createElement('button');b.className='file-item';const icon=document.createElement('span');icon.textContent=entry.directory?'▰':'▤';const label=document.createElement('span');label.textContent=entry.name;b.append(icon,label);b.onclick=()=>entry.directory?list(entry.path):read(entry.path);$('files-list').append(b);}if(!r.entries.length)$('files-list').textContent='This folder is empty.';paint();}catch(e){status(e.message);}}
 async function read(path){try{const r=await task({action:'read',path});$('editor-name').value=r.path;$('editor-text').value=r.text;app('editor');}catch(e){status(e.message);}}
 async function save(){const r=await task({action:'write',path:$('editor-name').value,text:$('editor-text').value});$('editor-name').value=r.path;paint();return r;}
 async function run(line){if(!line.trim()||busy)return;history.push(line);historyIndex=history.length;log('\n'+$('terminal-prompt').textContent+' '+line+'\n');$('terminal-command').value='';if(line.trim()==='clear'){$('terminal-output').textContent='';return;}try{const r=await task({action:'shell',line});log(r.output);}catch(e){log(e.message+'\n');}finally{$('terminal-command').focus();}}
 for(const b of document.querySelectorAll('[data-app]'))b.onclick=()=>app(b.dataset.app);
 $('terminal-form').onsubmit=e=>{e.preventDefault();run($('terminal-command').value);};
 $('terminal-command').onkeydown=e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();historyIndex=Math.max(0,Math.min(history.length,historyIndex+(e.key==='ArrowUp'?-1:1)));$('terminal-command').value=history[historyIndex]||'';}if(e.ctrlKey&&e.key==='c'){e.preventDefault();halt();}};
 $('runtime-stop').onclick=halt;$('desktop-power').onclick=()=>power(device);
 $('files-go').onclick=()=>list($('files-path').value);$('files-up').onclick=()=>list(folder.slice(0,folder.lastIndexOf('/'))||'/');
 $('file-new').onclick=()=>{$('editor-name').value=folder+'/untitled.txt';$('editor-text').value='';app('editor');};
 $('editor-save').onclick=()=>save().catch(e=>status(e.message));
 $('editor-run').onclick=async()=>{if(busy)return;app('terminal');log('\n▶ Running editor buffer\n');try{await save();const r=await task({action:'run',code:$('editor-text').value});log(r.output);}catch(e){log(e.message+'\n');}};
 $('editor-export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([$('editor-text').value],{type:'text/plain'}));a.download=$('editor-name').value.split('/').pop()||'studio.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 $('editor-text').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='s'){e.preventDefault();save().catch(e=>status(e.message));}if(e.key==='Tab'){e.preventDefault();const t=e.target;t.setRangeText('    ',t.selectionStart,t.selectionEnd,'end');}};
 $('open-hello').onclick=()=>read('/home/studio/hello.py');
 const clock=()=>{$('desktop-clock').textContent=new Date().toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});};clock();setInterval(clock,30000);
 fetch(new URL('./remote.json',import.meta.url)).then(r=>r.json()).then(config=>{if(config.enabled&&config.url.startsWith('wss://'))remoteConfig=config;}).catch(()=>{});
 $('remote-login').onsubmit=async e=>{e.preventDefault();if(!remoteConfig){$('remote-status').textContent='Ubuntu is not configured yet. The local workspace remains available.';return;}const password=$('remote-password').value;$('remote-status').textContent='Connecting…';try{if(!remote){const {remoteDesktop}=await import('./remote.js');remote=remoteDesktop({target:$('remote-display'),shouldCapture:()=>active&&powered&&currentApp==='remote',onFrame:image=>{if(active&&powered&&currentApp==='remote')preview(device,image);},onState:text=>{$('remote-status').textContent=text;status(text);const connected=text.includes('· connected');$('remote-login').hidden=connected;$('remote-display').hidden=!connected;if(connected)remote.focus();}});}remote.connect(remoteConfig.url,password);$('remote-password').value='';}catch(error){$('remote-status').textContent='Could not connect: '+error.message;}};
 $('remote-disconnect').onclick=()=>remote?.disconnect();$('remote-keyboard').onclick=()=>{$('remote-typing').hidden=!$('remote-typing').hidden;if(!$('remote-typing').hidden)$('remote-typing').focus();else remote?.focus();};$('remote-terminal').onclick=()=>remote?.terminal();$('remote-typing').oninput=e=>{if(e.isComposing)return;if(e.inputType==='deleteContentBackward')remote?.key(0xff08);else if(e.data||e.target.value)remote?.text(e.data||e.target.value);e.target.value='';};$('remote-typing').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();remote?.key(0xff0d);}if(e.key==='Backspace'&&!e.target.value){e.preventDefault();remote?.key(0xff08);}};
 function update(d){device=d.id;powered=d.power;$('desktop-device').textContent=names[device]||device;$('desktop').classList.toggle('screen-off',!powered);$('desktop-power').textContent=powered?'⏻ Power off':'⏻ Power on';$('desktop-power').setAttribute('aria-pressed',String(powered));$('desktop-off').hidden=powered;$('desktop-body').inert=!powered;}
 $('editor-text').addEventListener('input',paint);
 app('home');
 return {open(d){active=true;update(d);app('home');},close(){paintNow();active=false;clearTimeout(paintTimer);},update,halt};
}
