export const isPhone=id=>id==='phone'||id==='benchphone';
export function createPhone({power}){
 const $=id=>document.getElementById(id),dialog=$('phone-viewer'),body=$('phone-content');let device='phone',powered=true,locked=true,app='home',photo=0,expression='';
 const drawings=['still-life','tiger','itachi','david','portrait'];
 const time=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});
 function show(name){app=name;body.replaceChildren();$('phone-back').hidden=name==='home'||locked;dialog.classList.toggle('phone-locked',locked);if(!powered){body.innerHTML='<div class="phone-off">Screen off<br><button id="phone-wake">Power on</button></div>';$('phone-wake').onclick=()=>power(device);return;}
 if(locked){body.innerHTML='<button class="phone-lock" id="phone-unlock"><span class="phone-date"></span><strong class="phone-time"></strong><span class="lock-hint">Swipe up or tap to unlock ↑</span></button>';$('phone-unlock').onclick=()=>{locked=false;show('home');};clock();return;}
 if(name==='home'){body.innerHTML='<div class="phone-widget"><small>MAKE YOURSELF AT HOME</small><h2>Good ideas<br>start here.</h2><span class="phone-date"></span></div><div class="phone-app-grid"></div>';for(const [id,icon,label] of [['notes','✎','Notes'],['photos','▧','Photos'],['clock','◷','Clock'],['calculator','＋','Calculator']]){const b=document.createElement('button');b.dataset.phoneApp=id;b.innerHTML=`<span class="phone-icon ${id}">${icon}</span>${label}`;b.onclick=()=>show(id);body.querySelector('.phone-app-grid').append(b);}clock();}
 if(name==='notes'){body.innerHTML='<h2>Notes</h2><p class="phone-caption">A little thought for later.</p><textarea id="phone-note" placeholder="Write something…" aria-label="Phone note"></textarea><p id="phone-note-status" class="phone-caption">Saved on this device.</p>';try{$('phone-note').value=localStorage.getItem('bb-phone-note:'+device)||'';}catch{}$('phone-note').oninput=()=>{try{localStorage.setItem('bb-phone-note:'+device,$('phone-note').value);$('phone-note-status').textContent='Saved';}catch{$('phone-note-status').textContent='Storage unavailable';}};}
 if(name==='photos'){body.innerHTML='<h2>Studio drawings</h2><div class="phone-photo"><img alt="Studio drawing collection" src="assets/art/'+drawings[photo]+'-paper.png?v=13"></div><div class="phone-photo-nav"><button id="phone-photo-prev" aria-label="Previous photo">←</button><span>'+(photo+1)+' / 5</span><button id="phone-photo-next" aria-label="Next photo">→</button></div>';$('phone-photo-prev').onclick=()=>{photo=(photo+4)%5;show('photos');};$('phone-photo-next').onclick=()=>{photo=(photo+1)%5;show('photos');};}
 if(name==='clock'){body.innerHTML='<h2>Clock</h2><div class="phone-clock-face"><strong class="phone-time"></strong><span class="phone-date"></span><small>Your local time</small></div>';clock();}
 if(name==='calculator'){body.innerHTML='<h2>Calculator</h2><output id="phone-calc">'+(expression||'0')+'</output><div class="phone-keypad"></div>';for(const value of ['C','⌫','÷','×','7','8','9','−','4','5','6','+','1','2','3','=','0','.']){const b=document.createElement('button');b.textContent=value;b.onclick=()=>calc(value);body.querySelector('.phone-keypad').append(b);}}
 }
 // Evaluate only decimal arithmetic; no executable text or global evaluation.
 function calc(value){if(value==='C')expression='';else if(value==='⌫')expression=expression.slice(0,-1);else if(value==='='){try{const tokens=expression.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').match(/(?:\d*\.)?\d+|[+*/-]/g)||[];let total=0,term=0,op='+';let expectNumber=true;for(const t of tokens){if(expectNumber){const n=Number(t);if(!Number.isFinite(n))throw 0;if(op==='+')term=n;if(op==='-')term=-n;if(op==='*')term*=n;if(op==='/')term/=n;expectNumber=false;}else{if(!'+-*/'.includes(t))throw 0;if(t==='+'||t==='-'){total+=term;term=0;}op=t;expectNumber=true;}}if(expectNumber)throw 0;const n=total+term;expression=Number.isFinite(n)?String(Number(n.toFixed(8))):'Error';}catch{expression='Error';}}else{if(expression==='Error')expression='';if(expression.length<28)expression+=value;}$('phone-calc').textContent=expression||'0';}
 function clock(){for(const e of dialog.querySelectorAll('.phone-time'))e.textContent=time();for(const e of dialog.querySelectorAll('.phone-date'))e.textContent=new Date().toLocaleDateString([],{weekday:'long',month:'short',day:'numeric'});$('phone-status-time').textContent=time();}
 $('phone-home').onclick=()=>{if(powered){locked=false;show('home');}};$('phone-back').onclick=()=>show('home');$('phone-lock-button').onclick=()=>{locked=true;show('home');};$('phone-power').onclick=()=>power(device);
 let startY=null;body.addEventListener('pointerdown',e=>startY=e.clientY);body.addEventListener('pointerup',e=>{if(locked&&powered&&startY!==null&&startY-e.clientY>35){locked=false;show('home');}startY=null;});
 setInterval(()=>{if(dialog.open)clock();},30000);
 function update(d){if(!isPhone(d.id))return;device=d.id;powered=d.power;$('phone-title').textContent=d.id==='benchphone'?'Workbench phone':'Studio phone';$('phone-power').textContent=powered?'Power off':'Power on';$('phone-home').disabled=!powered;$('phone-lock-button').disabled=!powered;show(app);}
 return {open(d){locked=true;app='home';update(d);clock();},update,close(){locked=true;}};
}
